# LiveKit ports reference:
# https://docs.livekit.io/transport/self-hosting/ports-firewall/
# TURN/TLS-only proxying for LiveKit.

upstream livekit_turn_tls {
    server livekit:5349;
}

server {
    listen 5349;
    proxy_pass livekit_turn_tls;
    proxy_timeout 10m;
    proxy_connect_timeout 5s;
    proxy_upload_rate 32k;
    proxy_download_rate 32k;
}
